version: "3.9"

networks:
    stargaze:
        name: stargaze
        driver: bridge

services:
    node:
        container_name: node
        image: node
        build:
            context: .
        environment:
            NODE_ENV: ${NODE_ENV:-development}
        command: npm run start:${NODE_ENV:-development}
        volumes:
            - ./:/app
            - /app/node_modules
        healthcheck:
            test: [CMD, curl, -f, http://localhost]
            interval: 30s
            timeout: 10s
            retries: 3
        restart: unless-stopped
        ports:
            - 80:3000
        networks:
            - stargaze
